### ISSUE TITLE
Support services outside of a request context

### ISSUE THREAD

**Issue by dstufft** [mmerickel/pyramid_services#1]
Currently this assumes that the only use of looking up services will be inside of a request context. This is certainly the most common case but I have a case where It would be beneficial to be able to look up the registered service when I don't have a request (such as in an async worker or in a batch script).

Looking at the implementation, it appears that even for already created services (e.g. `register_service`) a dummy factory is created which does nothing but return the already created service. So I think for this to work, when you're not operating inside of a request, then request would be set to None.

I've copy/pasted the `find_service` function into my own app to see if I can make it work, and this appears to work:

``` python
def find_service(registry, iface=None, context=None, name=''):
    if iface is None:
        iface = Interface
    if name is None:
        name = ''

    context_iface = providedBy(context)
    svc_types = (IServiceClassifier, context_iface)
    svc_factory = registry.adapters.lookup(svc_types, iface, name=name)
    if svc_factory is None:
        raise ValueError('could not find registered service')
    # We are not operating in the confines of a request, so we'll pass a
    # None for the request.
    return svc_factory(context, None)
```

I'm not sure what the best API would be for using this outside of a request context, I originally thought that a config directive like `config.find_service()` would work, but the `#pyramid` IRC channel didn't seem to think that was the right way to go. There's no cache that'll return the same object for multiple `find_service` calls with this, since there is no request/response cycle to tie the lifetime of that cache to.

Thoughts? Is this something that would be useful to have inside of pyramid_services or should I just keep a copy of my `find_services` function inside of my app?

**Comment by aodag** [comment]
you should see `pyramid.paster.bootstrap`.
- http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/api/paster.html#pyramid.paster.bootstrap
- http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/commandline.html#writing-a-script

**Comment by mmerickel** [comment]
I intended for `pyramid_services` to be used in the context of a pyramid application. The services themselves are reusable elsewhere but probably by some mechanism other than this library.

The definition of a "pyramid application" can be stretched into the domain of scripts/etc that do not have a request object via the use of the mechanisms documented above (thanks @aodag). For example, `pyramid.paster.bootstrap` gives you a valid request object that you can use as if you were in a view. If you are in a thread and don't want to run bootstrap there is also `pyramid.scripting.prepare`.

With this in mind I don't see a good reason to support a function that ignores the request. There's always a request in pyramid-land.

As far as `config.find_service` goes that's more interesting. It's problematic because it would only work after invoking `config.commit` but I'd be happy to add a directive that supports doing the query.

**Comment by mmerickel** [comment]
I just pushed #4 to a working branch. It has no tests/docs yet, but was wondering if it'd help.
